services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5455:5432
    volumes:
      - syncra-data:/var/lib/postgresql/data
    networks:
      - syncra-backend

  database_manager:
    image: dpage/pgadmin4
    container_name: db_manager
    environment:
      PGADMIN_DEFAULT_EMAIL: user@syncra.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5555:80
    depends_on:
      - postgres
    volumes:
      - db_manager:/var/lib/pgadmin
    networks:
      - syncra-backend

volumes:
  syncra-data:
  db_manager:

networks:
  syncra-backend:
    driver: bridge