name: Build Docker Image for Frontend Dev

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [closed]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Extract Syncra Backend Version
              id: package-version
              run: |
                PACKAGE_VERSION=$(node -p "require('./package.json').version")
                echo "VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT 
            
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: |
                  izzy850/syncra-backend:latest
                  izzy850/syncra-backend:${{ steps.package-version.outputs.VERSION }}
                  izzy850/syncra-backend:${{ github.sha }}

            
