name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_and_push:
    if: >-
      github.event.pull_request.merged == true &&
      (
        startsWith(github.event.pull_request.head.ref, 'dev') ||
        startsWith(github.event.pull_request.head.ref, 'dependabot/') ||
        startsWith(github.event.pull_request.head.ref, 'hotfix/')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/syncra-backend
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max