name: Merge Dependabot PR
on:
  pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Debug PR Info
        run: |
          echo 'PR URL: $PR_URL'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Approve PR
        if: steps.metadata.outputs.dependabot == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.dependabot == 'true'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
