name: Linting and Formatting

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  linter-and-formatter:
    name: Linter and Formatter 
    strategy:
      matrix:
        node: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
    
      - name: Install dependencies
        run: pnpm install
      
      - name: Run Linter Check
        id: linter
        run: |
          pnpm run lint:check
        continue-on-error: true

      - name: Run Formatter Check
        id: formatter
        run: |
          pnpm run format:check
        continue-on-error: true
      
      - name: Run report of results
        if: always()
        run: |
          echo "Linter result: ${{ steps.linter.outcome }}"
          echo "Formatter result: ${{ steps.formatter.outcome }}"
