name: Linting and Formatting

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  linter-and-formatter:
    name: Linter and Formatter 
    strategy:
      matrix:
        node: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      
      - name: Install pnpm
        run: |
          npm install -g pnpm
          echo "::add-path::$(pnpm bin)" # Add pnpm binaries to PATH
      
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format
      - run: pnpm run lint
      
      - name: Run Linter
        id: linter
        run: |
          pnpm run lint:check
        continue-on-error: true

      - name: Run Formatter
        id: formatter
        run: |
          pnpm run format:check
        continue-on-error: true
      
      - name: Run report of results
        if: always()
        run: |
          echo "Linter result: ${{ steps.linter.outcome }}"
          echo "Formatter result: ${{ steps.formatter.outcome }}"
